CREATE TABLE IF NOT EXISTS translation_questions_easy
(
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    english_word   TEXT NOT NULL,
    german_word    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS translation_questions_medium
(INSERT INTO translation_questions_hard (english_word, german_word) VALUES ('to elucidate', 'erläutern'),
                                                                          ('ambiguous', 'vieldeutig'),
                                                                          ('bureaucratic', 'bürokratisch'),
                                                                          ('convoluted', 'verwickelt'),
                                                                          ('to scrutinize', 'prüfen'),
                                                                          ('to hypothesize', 'hypothetisieren'),
                                                                          ('paradoxical', 'paradox'),
                                                                          ('to extrapolate', 'extrapolieren'),
                                                                          ('to disseminate', 'verbreiten'),
                                                                          ('to conceptualize', 'konzeptualisieren'),
                                                                          ('to arbitrate', 'schlichten'),
                                                                          ('to circumvent', 'umgehen'),
                                                                          ('to undermine', 'untergraben'),
                                                                          ('to exacerbate', 'verschärfen'),
                                                                          ('to neutralize', 'neutralisieren'),
                                                                          ('to perpetuate', 'fortsetzen'),
                                                                          ('to invalidate', 'ungültig machen'),
                                                                          ('to marginalize', 'marginalisieren'),
                                                                          ('to optimize', 'optimieren'),
                                                                          ('to systematize', 'systematisieren'),
                                                                          ('to bureaucratize', 'bürokratisieren'),
                                                                          ('to decentralize', 'dezentralisieren'),
                                                                          ('to formalize', 'formalisieren'),
                                                                          ('to institutionalize', 'institutionalisieren'),
                                                                          ('to legitimize', 'legitimieren'),
                                                                          ('to rationalize', 'rationalisieren'),
                                                                          ('to standardize', 'standardisieren'),
                                                                          ('to synchronize', 'synchronisieren'),
                                                                          ('to automate', 'automatisieren'),
                                                                          ('to digitize', 'digitalisieren'),
                                                                          ('to globalize', 'globalisieren'),
                                                                          ('to privatize', 'privatisieren'),
                                                                          ('to reinvest', 'reinvestieren'),
                                                                          ('to subsidize', 'subventionieren'),
                                                                          ('to deregulate', 'deregulieren'),
                                                                          ('to monopolize', 'monopolisieren'),
                                                                          ('to liberalize', 'liberalisieren'),
                                                                          ('to nationalize', 'nationalisieren'),
                                                                          ('to outsource', 'auslagern'),
                                                                          ('to overregulate', 'überregulieren'),
                                                                          ('to underfund', 'unterfinanzieren'),
                                                                          ('to streamline', 'vereinfachen'),
                                                                          ('to upcycle', 'upcyceln'),
                                                                          ('to downsize', 'abbauen'),
                                                                          ('to restructure', 'restrukturieren'),
                                                                          ('to leverage', 'Hebelwirkung nutzen'),
                                                                          ('to amortize', 'abschreiben'),
                                                                          ('to hedge', 'absichern'),
                                                                          ('to diversify', 'diversifizieren'),
                                                                          ('to consolidate', 'konsolidieren'),
                                                                          ('to liquidate', 'liquidieren'),
                                                                          ('to recapitalize', 'Rekapitalisierung'),
                                                                          ('to arbitrage', 'Arbitrage'),
                                                                          ('to default', 'defaulten'),
                                                                          ('to depreciate', 'abschreiben'),
                                                                          ('to appreciate', 'wertsteigern'),
                                                                          ('to inflate', 'inflationieren'),
                                                                          ('to deflate', 'deflationieren'),
                                                                          ('to fluctuate', 'schwanken'),
                                                                          ('to stabilize', 'stabilisieren'),
                                                                          ('to oscillate', 'oszillieren'),
                                                                          ('to surge', 'anspringen'),
                                                                          ('to plummet', 'einbrechen'),
                                                                          ('to stagnate', 'stagnieren'),
                                                                          ('to rebound', 'zurückspringen'),
                                                                          ('to erode', 'abrutschen'),
                                                                          ('to dwindle', 'schrumpfen'),
                                                                          ('to escalate', 'eskalieren'),
                                                                          ('to mitigate', 'mildern'),
                                                                          ('to aggravate', 'verschärfen'),
                                                                          ('to counteract', 'gegenwirken'),
                                                                          ('to offset', 'ausgleichen'),
                                                                          ('to balance', 'ausgleichen'),
                                                                          ('to harmonize', 'harmonisieren'),
                                                                          ('to integrate', 'integrieren'),
                                                                          ('to fragment', 'fragmentieren'),
                                                                          ('to polarize', 'polarisieren'),
                                                                          ('to converge', 'zusammenlaufen'),
                                                                          ('to diverge', 'auseinanderlaufen'),
                                                                          ('to decouple', 'entkoppeln'),
                                                                          ('to interlink', 'verknüpfen'),
                                                                          ('to overlap', 'überlappen'),
                                                                          ('to intersect', 'kreuzen'),
                                                                          ('to correlate', 'korrelieren'),
                                                                          ('to causate', 'kausieren'),
                                                                          ('to reciprocate', 'zurückgeben'),
                                                                          ('to reciprocally influence', 'gegenseitig beeinflussen'),
                                                                          ('to synergize', 'synergisieren'),
                                                                          ('to maximize', 'maximieren'),
                                                                          ('to minimize', 'minimieren'),
                                                                          ('to obfuscate', 'verwirren'),
                                                                          ('to catalyze', 'katalysieren'),
                                                                          ('to ameliorate', 'verbessern'),
                                                                          ('to assuage', 'beschwichtigen'),
                                                                          ('to disabuse', 'enttäuschen'),
                                                                          ('the dichotomy', 'die Dichotomie'),
                                                                          ('the conundrum', 'das Rätsel'),
                                                                          ('the proclivity', 'die Neigung'),
                                                                          ('the paradigm', 'das Paradigma'),
                                                                          ('the scrutiny', 'die Prüfung'),
                                                                          ('the confluence', 'der Zusammenfluss'),
                                                                          ('the epiphany', 'die Erleuchtung'),
                                                                          ('the anomaly', 'die Anomalie'),
                                                                          ('the inertia', 'die Trägheit'),
                                                                          ('the juxtaposition', 'die Gegenüberstellung'),
('to perpetuate', 'aufrechterhalten'),
('to engender', 'hervorbringen'),
('to vindicate', 'rechtfertigen'),
('to corroborate', 'untermauern'),
('to obfuscate', 'verschleiern'),
('to capitulate', 'kapitulieren'),
('inextricable', 'unentwirrbar'),
('meticulous', 'akribisch'),
('ubiquitous', 'allgegenwärtig'),
('esoteric', 'esoterisch'),
('obsequious', 'unterwürfig'),
('taciturn', 'wortkarg'),
('capricious', 'launisch'),
('insidious', 'heimtückisch'),
('magnanimous', 'großmütig'),
('resilient', 'widerstandsfähig'),
('the inequity', 'die Ungerechtigkeit'),
('the resurgence', 'die Wiederauferstehung'),
('the culmination', 'der Höhepunkt'),
('the paradigm shift', 'der Paradigmenwechsel'),
('the hegemony', 'die Vorherrschaft'),
('the connoisseurship', 'die Kennerkenntnis'),
('the condescension', 'die Herablassung'),
('the reverberation', 'die Nachwirkung'),
('the insurrection', 'der Aufstand'),
('to juxtapose', 'gegenüberstellen'),
('to vacillate', 'schwanken'),
('to mollify', 'besänftigen'),
('to obviate', 'verhindern'),
('to supplant', 'ersetzen'),
('to subsume', 'einschließen'),
('to delineate', 'abgrenzen'),
('to venerate', 'verehren'),
('anachronistic', 'anachronistisch'),
('incongruous', 'inkongruent'),
('superfluous', 'überflüssig'),
('perfunctory', 'flüchtig'),
('cogent', 'überzeugend'),
('intransigent', 'kompromisslos'),
('vicissitudinous', 'wechselhaft'),
('pellucid', 'durchsichtig'),
('recalcitrant', 'widerborstig'),
('sagacious', 'klug'),
('the conjecture', 'die Vermutung'),
('the panacea', 'das Allheilmittel'),
('the obsolescence', 'die Veralterung'),
('the crescendo', 'die Steigerung'),
('the denouement', 'das Ende'),
('the attrition', 'die Abnutzung'),
('the litany', 'die Litanei'),
('the epitome', 'die Verkörperung'),
('the stratum', 'die Schicht'),
('the panoply', 'das Prachtstück'),
('to expound', 'darlegen'),
('to promulgate', 'veröffentlichen'),
('to renege', 'brechen'),
('to peregrinate', 'wandern'),
('to abrogate', 'abschaffen'),
('to exculpate', 'entlasten'),
('to truncate', 'kürzen'),
('to enthrall', 'fesseln'),
('inscrutable', 'unergründlich'),
('laconic', 'lakonisch'),
('obdurate', 'hartnäckig'),
('perspicacious', 'scharfsinnig'),
('turbulent', 'turbulent'),
('jejune', 'töricht');
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    english_word   TEXT NOT NULL,
    german_word    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS translation_questions_hard
(
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    english_word   TEXT NOT NULL,
    german_word    TEXT NOT NULL
);